dist: xenial
sudo: required
language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "arRu51ww4OYTmRc4lejsXVNR3e3gZD0B9u9d2rA1g3AKAM5P4sfU9h6bmL7zodp+6fZI1ButhnGph6FX7txf+vzhRPZVRPC7pPhr1BLhEsoEvC13hqd1vOSqPcZMaOC+F1wjzMIqGXtdKdfk0EohX
ulrfOlWXvoEV9ucuAOxUjKNYYdIZrWPZoNvERbc2qur+lACixhOw4RHaCUP+DzCk+5hZsmedsNE6I6wzbn/USyE5gcPaGTD9tshhZzVooUWBWKXdy5uy7fJy1G/j2Kkp3rtErSatgGLXb3V5hqDARLd7J4PX4S1o
ZAyA9iLErQ1xPkXlKKv7iuvz7+IjWCsO5upF5beTl0DHQ4NuJUPeEM1xi/b56Mo4Dg6YOSsSVLsf/mw/jdudpJb7LThAVOJnCaKHatDN88JX7dXRvbBiA1ZomLpJWIj+3TmDM2jhxVRjpSM9dihnUeCX3UNJYMqv
GTqTyBflCeMvLhTtVnct2nZX/HP6/mZnWBYwSyKejCnEK9Y0GFe3gS3TZ5zEvj8/iwXA3xMJct04FplJIhmyCVtmyu69KnFS3yo3C6t0d+0aV7sVV35sbWtoQsnrBttoXjlX6dobG4s7ULvPk92zUSdvv8/LC6OJ
MSauLvDxBVkyDSgA4ccYJMwom2Ir7ZJQoGQaDNwY5Lg+IyZWz2EUbQ="

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn test -B -P coverage
      after_success:
        - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - stage: test
      jdk: openjdk11
      script:
        - mvn test -B
    - stage: test
      jdk: openjdk12
      script:
        - mvn test -B
